#!/usr/bin/python3

import threading, argparse, pyfiglet, ipaddress, socket, time, sys, re
from concurrent.futures import ThreadPoolExecutor

def banner():
        print(pyfiglet.figlet_format("RevLookup"), file=sys.stderr)
        print("[>] Versão: 1.2", file=sys.stderr)
        print("[$] Coded By HunterDep", file=sys.stderr)
        print("[@] Github: https://github.com/yHunterDep\n", file=sys.stderr)
        time.sleep(1)

def scan(i):
	try:
                    if re.fullmatch(regex_domain, i):
                            ips = socket.gethostbyname_ex(i)[2]
                            for ip in ips:
                                    host = socket.gethostbyaddr(ip)
                                    print(host[0], flush=True)
                                    if args.output:
                                            with open(args.output, "a+") as f:
                                                f.write(host[0]+"\n")
                    else:
                            host = socket.gethostbyaddr(i)
                            print(host[0], flush=True)

                            if args.output:
                                    with open(args.output, "a+") as f:
	                                    f.write(host[0]+"\n")
        	                            f.close()
	except Exception as x:
		pass

regex_ip = r"\d{1,3}(?:\.\d{1,3}){3}"
regex_cidr = r"\d{1,3}(?:\.\d{1,3}){3}/\d+"
regex_domain = r"([a-zA-Z0-9]+\.?)+\.[a-zA-Z]{2,}"

parser = argparse.ArgumentParser(description="Revlookup 1.2 - HunterDep")
parser.add_argument("-target", "--target", help="Target IP address or domain to perform reverse lookup (e.g., 72.217.29.238 or google.com)")
parser.add_argument("-targets", "--targets", help="File containing IPs, domains, or CIDR ranges for reverse lookup (e.g., targets.txt)")
parser.add_argument("-cidr", "--cidr", help="CIDR range to perform reverse lookup (e.g., 87.248.98.0/24)")
parser.add_argument("-c", "--concurrent", type=int, help="Set the number of concurrent threads to use during scanning (default: 25)", default=25)
parser.add_argument("-o", "--output", help="Output file to save results")
parser.add_argument("-s", "--silent", help="Silent mode (disable banner)", action="store_true")

args = parser.parse_args()

t, ts = args.target, args.targets
cidr = args.cidr
silent = args.silent

if not silent:
        banner()

if t and ts:
        print("[?] Use o '-t' ou '-targets'")
        quit()

if t:
	scan(t)

elif cidr:
        thrs = []
        ip_range = ipaddress.ip_network(cidr)
        ip_list = [str(ip) for ip in ip_range.hosts()]

        with ThreadPoolExecutor(max_workers=args.concurrent) as executor:
        	executor.map(scan, ip_list)

# Orientação
# Aqui se o usuário escolher o -targets, o programa vai ler o arquivo

# pra cada ip em ip_list, ele verifica se o ip é um ip normal, ex: 1.1.1.1, ai ele cria uma Thread e envia pro scan()
# se não for um ip normal (se tiver um CIDR), ele vai resolver o CIDR, criando uma nova lista (ip_list2), e pra cada um, ele criará um thread e enviará pro scan()

if ts:
        f_list = open(ts, "r+").readlines()
        f_list = [x.strip() for x in f_list]

        workers = []

        for tgt in f_list:
                try:
                        ### IP NORMAL ###
                        if re.fullmatch(regex_ip, tgt):
                                workers.append(tgt)

                        ### CIDR ###
                        elif re.fullmatch(regex_cidr, tgt):
                                ip_range = ipaddress.ip_network(tgt)
                                ip_list = [str(ip) for ip in ip_range.hosts()]
                                workers.extend(ip_list)

			## DOMAIN ##
                        elif re.fullmatch(regex_domain, tgt):
                                workers.extend(tgt.split())
                except Exception as x:
                    pass
        with ThreadPoolExecutor(max_workers=args.concurrent) as executor:
                executor.map(scan, workers)
